import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { GET_CALCULATOR } from '~/src/queries/get_calculator';
import { Calculadora, RootQuery } from '~/src/types/wp-graphql';
import { authenticatedClient } from '~/src/utils/apollo-client';
import { getFooter } from '~/src/utils/getFooter';
import { getRelatedCalculatorsById } from '~/src/utils/getRelatedCalculatorsById';
import { idsCalculatorsByCategory } from '~/src/utils/idsCalculatorsByCategory';
import { processMegaMenu } from '~/src/utils/processMegaMenu';

export const getStaticProps: GetStaticProps = async () => {
	const { data } = await authenticatedClient(
		`${process.env.WP_JWT_AUTH_TOKEN}`
	).query<RootQuery>({
		query: GET_CALCULATOR,
		variables: { uri: 'calculadora-dias-uteis' },
	});

	const menuData = processMegaMenu(data.menus);
	const { footerData } = await getFooter();

	const nameCategoryCalculator =
		data.calculadora?.calculadorasCategorias?.nodes?.[0]?.name;

	const { idsCalculators } = idsCalculatorsByCategory(nameCategoryCalculator);

	const relatedCalculators =
		data.calculadora?.customFieldCalculadoras?.relacionadas ??
		(await getRelatedCalculatorsById(idsCalculators));

	const meta: WordPressMetaData = {
		pageId: data.calculadora?.calculadoraId ?? 0,
		pageType: data.calculadora?.__typename,
		related: relatedCalculators as Calculadora[],
	};

	return {
		props: {
			data: data.page,
		},
	};
};

interface IHomeProps {
	data: any;
}

const Home: NextPage<IHomeProps> = props => {
	const { data } = props;

	return (
		<div>
			<Head>
				<title>Stitches</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main></main>
		</div>
	);
};

export default Home;
