import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import HeaderImage from '~public/img/header-default-image.png';
import DOMPurify from 'isomorphic-dompurify';
import { GET_PAGE } from '~src/queries/get_page';
import {
	Heading1,
	Heading2,
	HeaderStack,
	ContactContentStack,
} from '../components';
import { client } from '../utils/apollo-client';

export const getStaticProps: GetStaticProps = async () => {
	const { data } = await client.query({
		query: GET_PAGE,
		variables: { uri: '/contato' },
	});

	return {
		props: {
			data: data.page,
		},
	};
};

interface IHomeProps {
	data: any;
}

const Home: NextPage<IHomeProps> = props => {
	const { data } = props;

	return (
		<div>
			<Head>
				<title>Stitches</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div>
					{data.title && data.bannerPaginasInternas?.subtitulo && (
						<HeaderStack>
							<Image src={HeaderImage} alt='Header' />
							<Heading1
								css={{
									paddingBottom: '2rem',
									paddingTop: '3rem',
								}}
							>
								{data.title}
							</Heading1>
							<Heading2>{data.bannerPaginasInternas?.subtitulo}</Heading2>
						</HeaderStack>
					)}

					<ContactContentStack
						dangerouslySetInnerHTML={{
							__html: DOMPurify.sanitize(data.content),
						}}
					/>
				</div>
			</main>
		</div>
	);
};

export default Home;
